const STORAGE_KEY = 'productos';
const STORAGE_VERSION_KEY = 'productos_version';
const CURRENT_VERSION = 11;

const laptopImages = {
  'Lenovo IdeaPad Gaming 3': new URL('../assets/Laptops/Lenovo IdeaPad Gaming 3.webp', import.meta.url).href,
  'ASUS TUF Gaming F15': new URL('../assets/Laptops/ASUS TUF Gaming F15.jfif', import.meta.url).href,
  'HP Victus 15': new URL('../assets/Laptops/HP Victus 15.avif', import.meta.url).href,
  'Acer Nitro 5': new URL('../assets/Laptops/Acer Nitro 5.webp', import.meta.url).href,
  'MSI GF63 Thin': new URL('../assets/Laptops/MSI GF63 Thin.jpg', import.meta.url).href,
  'Lenovo Legion 5': new URL('../assets/Laptops/Lenovo Legion 5.jpg', import.meta.url).href,
};

const pcGamerImages = {
  'Torre Gamer ASUS ROG Strix': new URL('../assets/PCGamer/Torre Gamer ASUS ROG Strix.jfif', import.meta.url).href,
  'PC Gaming MSI Infinite RS': new URL('../assets/PCGamer/PC Gaming MSI Infinite RS.jfif', import.meta.url).href,
  'HP OMEN 35L Desktop': new URL('../assets/PCGamer/HP OMEN 35L Desktop.jfif', import.meta.url).href,
  'Lenovo Legion Tower 5': new URL('../assets/PCGamer/Lenovo Legion Tower 5.avif', import.meta.url).href,
  'Acer Predator Orion 5000': new URL('../assets/PCGamer/Acer Predator Orion 5000.jfif', import.meta.url).href,
  'PC Gamer Ryzen 9 RTX 4080': new URL('../assets/PCGamer/PC Gamer Ryzen 9 RTX 4080.avif', import.meta.url).href,
};
const celularesImages = {
  'iPhone 15 Pro Max 256GB': new URL('../assets/Celulares/iPhone 15 Pro Max 256GB.jfif', import.meta.url).href,
  'Samsung Galaxy S24 Ultra': new URL('../assets/Celulares/Samsung Galaxy S24 Ultra.jfif', import.meta.url).href,
  'Samsung Galaxy A54 5G': new URL('../assets/Celulares/Samsung Galaxy A54 5G.jfif', import.meta.url).href,
  'Xiaomi 13T Pro': new URL('../assets/Celulares/Xiaomi 13T Pro.png', import.meta.url).href,
  'Motorola Edge 40 Pro': new URL('../assets/Celulares/Motorola Edge 40 Pro.jfif', import.meta.url).href,
  'Google Pixel 8 Pro': new URL('../assets/Celulares/Google Pixel 8 Pro.jfif', import.meta.url).href,
};

const accesoriosImages = {
  'Funda Silicone Premium iPhone 15': new URL('../assets/Accesorios/Funda Silicone Premium iPhone 15.jfif', import.meta.url).href,
  'Cargador USB-C GaN 65W': new URL('../assets/Accesorios/Cargador USB-C GaN 65W.webp', import.meta.url).href,
  'Auriculares Bluetooth Pro Max': new URL('../assets/Accesorios/Auriculares Bluetooth Pro Max.jfif', import.meta.url).href,
  'Cable USB-C Premium 2m': new URL('../assets/Accesorios/Cable USB-C Premium 2m.jfif', import.meta.url).href,
  'Soporte Magnético para Auto': new URL('../assets/Accesorios/Soporte Magnético para Auto.jfif', import.meta.url).href,
  'Powerbank 20000mAh 65W': new URL('../assets/Accesorios/Powerbank 20000mAh 65W.jfif', import.meta.url).href,
};

const componentesImages = {
  'SSD NVMe 2TB Kingston': new URL('../assets/Componentes/SSD NVMe 2TB Kingston.jfif', import.meta.url).href,
  'Tarjeta Madre ASUS ROG Strix B650E': new URL('../assets/Componentes/Tarjeta Madre ASUS ROG Strix B650E.jfif', import.meta.url).href,
  'RAM DDR5 32GB Corsair Vengeance': new URL('../assets/Componentes/RAM DDR5 32GB Corsair Vengeance.jfif', import.meta.url).href,
  'Fuente 850W 80+ Gold Corsair': new URL('../assets/Componentes/Fuente 850W 80+ Gold Corsair.jfif', import.meta.url).href,
  'Procesador AMD Ryzen 7 7800X3D': new URL('../assets/Componentes/Procesador AMD Ryzen 7 7800X3D.jpg', import.meta.url).href,
  'Cooler CPU Noctua NH-D15': new URL('../assets/Componentes/Cooler CPU Noctua NH-D15.jfif', import.meta.url).href,
};

const perifericosImages = {
  'Auriculares Gamer RGB 7.1': new URL('../assets/Perifericos/Auriculares Gamer RGB 7.1.jpg', import.meta.url).href,
  'Mouse Óptico Gamer 16000 DPI': new URL('../assets/Perifericos/Mouse Óptico Gamer 16000 DPI.webp', import.meta.url).href,
  'Teclado Mecánico RGB Switch Red': new URL('../assets/Perifericos/Teclado Mecánico RGB Switch Red.webp', import.meta.url).href,
  'Monitor Curvo 27\'\' 165Hz Gaming': new URL('../assets/Perifericos/Monitor Curvo 27\'\' 165Hz Gaming.jfif', import.meta.url).href,
  'Webcam Full HD 1080p': new URL('../assets/Perifericos/Webcam Full HD 1080p.jfif', import.meta.url).href,
  'Mousepad Gamer XL RGB': new URL('../assets/Perifericos/Mousepad Gamer XL RGB.jpg', import.meta.url).href,
};

const gamingImages = {
  'Silla Gamer Ergonómica RGB': new URL('../assets/Gaming/Silla Gamer Ergonómica RGB.webp', import.meta.url).href,
  'Control Xbox Wireless Carbon Black': new URL('../assets/Gaming/Control Xbox Wireless Carbon Black.jpg', import.meta.url).href,
  'Joystick Thrustmaster T300 RS GT': new URL('../assets/Gaming/Joystick Thrustmaster T300 RS GT.jfif', import.meta.url).href,
  'Consola Portátil Steam Deck 512GB': new URL('../assets/Gaming/Consola Portátil Steam Deck 512GB.webp', import.meta.url).href,
  'Escritorio Gamer RGB 140cm': new URL('../assets/Gaming/Escritorio Gamer RGB 140cm.jfif', import.meta.url).href,
  'Lente Cámara Streaming 4K': new URL('../assets/Gaming/Lente Cámara Streaming 4K.jfif', import.meta.url).href,
};

const ofertasImages = {
  'Samsung Galaxy S24 128GB': new URL('../assets/Celulares/Samsung Galaxy S24 Ultra.jfif', import.meta.url).href,
  'iPhone 14 128GB': new URL('../assets/Celulares/iPhone 15 Pro Max 256GB.jfif', import.meta.url).href,
  'ASUS TUF Gaming F15 RTX 4050': new URL('../assets/Laptops/ASUS TUF Gaming F15.jfif', import.meta.url).href,
  'Teclado Logitech MX Keys S': new URL('../assets/Perifericos/Teclado Mecánico RGB Switch Red.webp', import.meta.url).href,
  'Monitor LG 27\'\' 4K UHD': new URL('../assets/Ofertas/Monitor LG 27\'\' 4K UHD.avif', import.meta.url).href,
  'Auriculares Sony WH-1000XM5': new URL('../assets/Accesorios/Auriculares Bluetooth Pro Max.jfif', import.meta.url).href,
  'Monitor Curvo 27\'\' 165Hz Gaming': new URL('../assets/Ofertas/Monitor Curvo 27\'\' 165Hz Gaming.jfif', import.meta.url).href,
};

const productosIniciales = [
  // ==================== LAPTOPS (6) ====================
  {
    id: 1,
    name: "Lenovo IdeaPad Gaming 3",
    image: laptopImages['Lenovo IdeaPad Gaming 3'],
    category: "laptops",
    categoryLabel: "Laptops",
    price: 749990,
    priceFormatted: "$749.990",
    imageBg: "cyan-blue",
    description: "Notebook gamer con Ryzen 5, 8GB RAM, RTX 3050, SSD 512GB. Pantalla IPS 15.6'' Full HD 120Hz.",
    specs: ["Ryzen 5 5600H", "8GB DDR4", "RTX 3050 4GB", "512GB SSD", "15.6'' FHD 120Hz"],
    destacado: true,
    oferta: false,
    brand: "Lenovo",
    discount: 15,
    badgeType: "discount",
    rating: 4.5,
    reviews: 124,
    stock: 15
  },
  {
    id: 2,
    name: "ASUS TUF Gaming F15",
    image: laptopImages['ASUS TUF Gaming F15'],
    category: "laptops",
    categoryLabel: "Laptops",
    price: 1299990,
    priceFormatted: "$1.299.990",
    imageBg: "purple-indigo",
    description: "Notebook gamer con Intel i7, 16GB RAM, RTX 4060, SSD 1TB. Pantalla 15.6'' FHD 144Hz.",
    specs: ["Intel i7-12700H", "16GB DDR5", "RTX 4060 8GB", "1TB SSD", "15.6'' FHD 144Hz"],
    destacado: true,
    oferta: false,
    brand: "ASUS",
    discount: 0,
    badgeType: "new",
    rating: 4.8,
    reviews: 86,
    stock: 8
  },
  {
    id: 3,
    name: "HP Victus 15",
    image: laptopImages['HP Victus 15'],
    category: "laptops",
    categoryLabel: "Laptops",
    price: 1099990,
    priceFormatted: "$1.099.990",
    imageBg: "pink-purple",
    description: "Notebook gamer con Intel i5, 16GB RAM, RTX 4050, SSD 512GB. Pantalla 15.6'' FHD 144Hz.",
    specs: ["Intel i5-12500H", "16GB DDR4", "RTX 4050 6GB", "512GB SSD", "15.6'' FHD 144Hz"],
    destacado: true,
    oferta: true,
    brand: "HP",
    discount: 0,
    badgeType: "offer",
    rating: 4.3,
    reviews: 72,
    stock: 22
  },
  {
    id: 4,
    name: "Acer Nitro 5",
    image: laptopImages['Acer Nitro 5'],
    category: "laptops",
    categoryLabel: "Laptops",
    price: 999990,
    priceFormatted: "$999.990",
    imageBg: "cyan-teal",
    description: "Notebook gamer con Ryzen 7, 16GB RAM, RTX 3060, SSD 512GB. Pantalla 15.6'' FHD 165Hz.",
    specs: ["Ryzen 7 6800H", "16GB DDR5", "RTX 3060 6GB", "512GB SSD", "15.6'' FHD 165Hz"],
    destacado: true,
    oferta: false,
    brand: "Acer",
    discount: 10,
    badgeType: "discount",
    rating: 4.6,
    reviews: 64,
    stock: 12
  },
  {
    id: 5,
    name: "MSI GF63 Thin",
    image: laptopImages['MSI GF63 Thin'],
    category: "laptops",
    categoryLabel: "Laptops",
    price: 1199990,
    priceFormatted: "$1.199.990",
    imageBg: "blue-purple",
    description: "Notebook gamer delgada con Intel i7, 16GB RAM, RTX 4050, SSD 512GB.",
    specs: ["Intel i7-12650H", "16GB DDR4", "RTX 4050 6GB", "512GB SSD", "15.6'' FHD 144Hz"],
    destacado: true,
    oferta: false,
    brand: "MSI",
    discount: 0,
    badgeType: "new",
    rating: 4.7,
    reviews: 58,
    stock: 10
  },
  {
    id: 6,
    name: "Lenovo Legion 5",
    image: laptopImages['Lenovo Legion 5'],
    category: "laptops",
    categoryLabel: "Laptops",
    price: 1499990,
    priceFormatted: "$1.499.990",
    imageBg: "indigo-cyan",
    description: "Notebook gamer premium con Ryzen 7, 32GB RAM, RTX 4070, SSD 1TB. Pantalla 16'' QHD 165Hz.",
    specs: ["Ryzen 7 7745HX", "32GB DDR5", "RTX 4070 8GB", "1TB SSD", "16'' QHD 165Hz"],
    destacado: true,
    oferta: false,
    brand: "Lenovo",
    discount: 8,
    badgeType: "discount",
    rating: 4.4,
    reviews: 95,
    stock: 5
  },

  // ==================== PC GAMER (6) ====================
  {
    id: 7,
    name: "Torre Gamer ASUS ROG Strix",
    image: pcGamerImages['Torre Gamer ASUS ROG Strix'],
    category: "pc-gamer",
    categoryLabel: "PC Gamer",
    price: 1850000,
    priceFormatted: "$1.850.000",
    imageBg: "purple-indigo",
    description: "PC de escritorio gamer con Intel i7, 32GB RAM, RTX 4070 Ti. Torre con RGB y refrigeración líquida.",
    specs: ["Intel i7-13700K", "32GB DDR5", "RTX 4070 Ti 12GB", "1TB SSD NVMe", "Refrigeración líquida"],
    destacado: true,
    oferta: true,
    brand: "ASUS",
    discount: 0,
    badgeType: "offer",
    rating: 4.8,
    reviews: 86,
    stock: 7
  },
  {
    id: 8,
    name: "PC Gaming MSI Infinite RS",
    image: pcGamerImages['PC Gaming MSI Infinite RS'],
    category: "pc-gamer",
    categoryLabel: "PC Gamer",
    price: 2199990,
    priceFormatted: "$2.199.990",
    imageBg: "cyan-blue",
    description: "PC gamer con Intel i9, 32GB RAM DDR5, RTX 4080. Diseño premium con panel de cristal.",
    specs: ["Intel i9-13900K", "32GB DDR5", "RTX 4080 16GB", "2TB SSD NVMe", "Panel de cristal"],
    destacado: true,
    oferta: false,
    brand: "MSI",
    discount: 0,
    badgeType: "new",
    rating: 4.7,
    reviews: 45,
    stock: 3
  },
  {
    id: 9,
    name: "HP OMEN 35L Desktop",
    image: pcGamerImages['HP OMEN 35L Desktop'],
    category: "pc-gamer",
    categoryLabel: "PC Gamer",
    price: 1599990,
    priceFormatted: "$1.599.990",
    imageBg: "pink-purple",
    description: "PC gamer con Intel i7, 16GB RAM, RTX 4060 Ti. Torre compacta con RGB personalizable.",
    specs: ["Intel i7-13700F", "16GB DDR5", "RTX 4060 Ti 8GB", "1TB SSD", "RGB personalizable"],
    destacado: true,
    oferta: false,
    brand: "HP",
    discount: 12,
    badgeType: "discount",
    rating: 4.5,
    reviews: 78,
    stock: 18
  },
  {
    id: 10,
    name: "Lenovo Legion Tower 5",
    image: pcGamerImages['Lenovo Legion Tower 5'],
    category: "pc-gamer",
    categoryLabel: "PC Gamer",
    price: 1799990,
    priceFormatted: "$1.799.990",
    imageBg: "cyan-teal",
    description: "PC gamer con AMD Ryzen 7, 32GB RAM, RTX 4070. Torre elegante con excelente refrigeración.",
    specs: ["AMD Ryzen 7 7700X", "32GB DDR5", "RTX 4070 12GB", "1TB SSD NVMe", "Refrigeración air"],
    destacado: true,
    oferta: false,
    brand: "Lenovo",
    discount: 0,
    badgeType: "new",
    rating: 4.6,
    reviews: 52,
    stock: 9
  },
  {
    id: 11,
    name: "Acer Predator Orion 5000",
    image: pcGamerImages['Acer Predator Orion 5000'],
    category: "pc-gamer",
    categoryLabel: "PC Gamer",
    price: 1999990,
    priceFormatted: "$1.999.990",
    imageBg: "blue-purple",
    description: "PC gamer premium con Intel i9, 32GB RAM, RTX 4070 Ti. Enfriamiento líquido AIO.",
    specs: ["Intel i9-13900F", "32GB DDR5", "RTX 4070 Ti 12GB", "1TB SSD", "AIO 240mm"],
    destacado: true,
    oferta: false,
    brand: "Acer",
    discount: 5,
    badgeType: "discount",
    rating: 4.4,
    reviews: 63,
    stock: 6
  },
  {
    id: 12,
    name: "PC Gamer Ryzen 9 RTX 4080",
    image: pcGamerImages['PC Gamer Ryzen 9 RTX 4080'],
    category: "pc-gamer",
    categoryLabel: "PC Gamer",
    price: 2499990,
    priceFormatted: "$2.499.990",
    imageBg: "indigo-cyan",
    description: "PC gamer extremo con AMD Ryzen 9, 64GB RAM, RTX 4080. Para gaming y creación de contenido.",
    specs: ["AMD Ryzen 9 7950X", "64GB DDR5", "RTX 4080 16GB", "2TB SSD NVMe", "Refrigeración líquida 360mm"],
    destacado: true,
    oferta: true,
    brand: "ASUS",
    discount: 0,
    badgeType: "offer",
    rating: 4.9,
    reviews: 34,
    stock: 4
  },

  // ==================== CELULARES (6) ====================
  {
    id: 13,
    name: "iPhone 15 Pro Max 256GB",
    image: celularesImages['iPhone 15 Pro Max 256GB'],
    category: "celulares",
    categoryLabel: "Celulares",
    price: 1299990,
    priceFormatted: "$1.299.990",
    imageBg: "cyan-blue",
    description: "El iPhone más potente con chip A17 Pro, cámara de 48MP y cuerpo de titanio.",
    specs: ["A17 Pro", "256GB", "48MP Principal", "Titanio", "USB-C"],
    destacado: true,
    oferta: false,
    brand: "Lenovo",
    discount: 0,
    badgeType: "new",
    rating: 4.9,
    reviews: 200,
    stock: 30
  },
  {
    id: 14,
    name: "Samsung Galaxy S24 Ultra",
    image: celularesImages['Samsung Galaxy S24 Ultra'],
    category: "celulares",
    categoryLabel: "Celulares",
    price: 1199990,
    priceFormatted: "$1.199.990",
    imageBg: "purple-indigo",
    description: "Smartphone premium con S Pen, cámara de 200MP e IA integrada.",
    specs: ["Snapdragon 8 Gen 3", "256GB", "200MP Cámara", "S Pen incluido", "Titanio"],
    destacado: true,
    oferta: true,
    brand: "ASUS",
    discount: 10,
    badgeType: "discount",
    rating: 4.6,
    reviews: 150,
    stock: 25
  },
  {
    id: 15,
    name: "Samsung Galaxy A54 5G",
    image: celularesImages['Samsung Galaxy A54 5G'],
    category: "celulares",
    categoryLabel: "Celulares",
    price: 449990,
    priceFormatted: "$449.990",
    imageBg: "pink-purple",
    description: "Smartphone gama media con cámara de 50MP, batería de 5000mAh y pantalla Super AMOLED.",
    specs: ["Exynos 1380", "128GB", "50MP Cámara", "5000mAh", "6.4'' Super AMOLED"],
    destacado: false,
    oferta: true,
    brand: "HP",
    discount: 0,
    badgeType: "offer",
    rating: 4.4,
    reviews: 180,
    stock: 40
  },
  {
    id: 16,
    name: "Xiaomi 13T Pro",
    image: celularesImages['Xiaomi 13T Pro'],
    category: "celulares",
    categoryLabel: "Celulares",
    price: 599990,
    priceFormatted: "$599.990",
    imageBg: "cyan-teal",
    description: "Smartphone con cámara Leica, chip Dimensity 9200+ y carga turbo de 120W.",
    specs: ["Dimensity 9200+", "256GB", "50MP Leica", "120W Carga", "6.67'' 144Hz"],
    destacado: false,
    oferta: false,
    brand: "Acer",
    discount: 15,
    badgeType: "discount",
    rating: 4.5,
    reviews: 120,
    stock: 20
  },
  {
    id: 17,
    name: "Motorola Edge 40 Pro",
    image: celularesImages['Motorola Edge 40 Pro'],
    category: "celulares",
    categoryLabel: "Celulares",
    price: 549990,
    priceFormatted: "$549.990",
    imageBg: "blue-purple",
    description: "Smartphone premium con Snapdragon 8 Gen 2, cámara de 50MP y pantalla pOLED 165Hz.",
    specs: ["Snapdragon 8 Gen 2", "256GB", "50MP OIS", "125W Carga", "6.67'' pOLED 165Hz"],
    destacado: false,
    oferta: false,
    brand: "MSI",
    discount: 0,
    badgeType: "new",
    rating: 4.3,
    reviews: 95,
    stock: 15
  },
  {
    id: 18,
    name: "Google Pixel 8 Pro",
    image: celularesImages['Google Pixel 8 Pro'],
    category: "celulares",
    categoryLabel: "Celulares",
    price: 799990,
    priceFormatted: "$799.990",
    imageBg: "indigo-cyan",
    description: "Smartphone con la mejor cámara computacional, chip Tensor G3 y 7 años de actualizaciones.",
    specs: ["Tensor G3", "128GB", "50MP Principal", "5000mAh", "6.7'' LTPO OLED"],
    destacado: true,
    oferta: false,
    brand: "Lenovo",
    discount: 8,
    badgeType: "discount",
    rating: 4.7,
    reviews: 88,
    stock: 35
  },

  // ==================== ACCESORIOS (6) ====================
  {
    id: 19,
    name: "Funda Silicone Premium iPhone 15",
    image: accesoriosImages['Funda Silicone Premium iPhone 15'],
    category: "accesorios",
    categoryLabel: "Accesorios",
    price: 29990,
    priceFormatted: "$29.990",
    imageBg: "cyan-blue",
    description: "Funda de silicona premium para iPhone 15 con protección magnética y acabado suave.",
    specs: ["Silicona premium", "Imán MagSafe", "Colores variados", "Ultra delgada", "Anti-scratch"],
    destacado: false,
    oferta: true,
    brand: "ASUS",
    discount: 0,
    badgeType: "offer",
    rating: 4.2,
    reviews: 320,
    stock: 50
  },
  {
    id: 20,
    name: "Cargador USB-C GaN 65W",
    image: accesoriosImages['Cargador USB-C GaN 65W'],
    category: "accesorios",
    categoryLabel: "Accesorios",
    price: 45990,
    priceFormatted: "$45.990",
    imageBg: "purple-indigo",
    description: "Cargador rápido USB-C de 65W con tecnología GaN, compacto y compatible con notebooks y celulares.",
    specs: ["65W PD", "Tecnología GaN", "USB-C x2", "Compacto", "Universal"],
    destacado: true,
    oferta: false,
    brand: "HP",
    discount: 0,
    badgeType: "new",
    rating: 4.6,
    reviews: 185,
    stock: 45
  },
  {
    id: 21,
    name: "Auriculares Bluetooth Pro Max",
    image: accesoriosImages['Auriculares Bluetooth Pro Max'],
    category: "accesorios",
    categoryLabel: "Accesorios",
    price: 89990,
    priceFormatted: "$89.990",
    imageBg: "pink-purple",
    description: "Auriculares over-ear con cancelación de ruido activa, audio Hi-Res y 40hs de batería.",
    specs: ["ANC Activo", "Hi-Res Audio", "40hs batería", "Bluetooth 5.2", "Multipoint"],
    destacado: true,
    oferta: false,
    brand: "Acer",
    discount: 20,
    badgeType: "discount",
    rating: 4.4,
    reviews: 210,
    stock: 38
  },
  {
    id: 22,
    name: "Cable USB-C Premium 2m",
    image: accesoriosImages['Cable USB-C Premium 2m'],
    category: "accesorios",
    categoryLabel: "Accesorios",
    price: 19990,
    priceFormatted: "$19.990",
    imageBg: "cyan-teal",
    description: "Cable USB-C a USB-C de alta velocidad con carga de 100W y transferencia de datos.",
    specs: ["USB-C a USB-C", "100W Carga", "480Mbps datos", "2 metros", "Nylon trenzado"],
    destacado: false,
    oferta: true,
    brand: "MSI",
    discount: 0,
    badgeType: "offer",
    rating: 4.3,
    reviews: 450,
    stock: 55
  },
  {
    id: 23,
    name: "Soporte Magnético para Auto",
    image: accesoriosImages['Soporte Magnético para Auto'],
    category: "accesorios",
    categoryLabel: "Accesorios",
    price: 35990,
    priceFormatted: "$35.990",
    imageBg: "blue-purple",
    description: "Soporte magnético para celular en el auto con ventosa robusta y rotación 360°.",
    specs: ["Imán N52", "Rotación 360°", "Ventosa robusta", "Compatible MagSafe", "Metal + ABS"],
    destacado: false,
    oferta: false,
    brand: "Lenovo",
    discount: 10,
    badgeType: "discount",
    rating: 4.5,
    reviews: 165,
    stock: 28
  },
  {
    id: 24,
    name: "Powerbank 20000mAh 65W",
    image: accesoriosImages['Powerbank 20000mAh 65W'],
    category: "accesorios",
    categoryLabel: "Accesorios",
    price: 69990,
    priceFormatted: "$69.990",
    imageBg: "indigo-cyan",
    description: "Batería externa de 20000mAh con carga rápida 65W, ideal para notebooks y celulares.",
    specs: ["20000mAh", "65W PD", "USB-C x2", "Display LED", "Carga rápida"],
    destacado: true,
    oferta: false,
    brand: "ASUS",
    discount: 0,
    badgeType: "new",
    rating: 4.7,
    reviews: 130,
    stock: 32
  },

  // ==================== COMPONENTES (6) ====================
  {
    id: 25,
    name: "SSD NVMe 2TB Kingston",
    image: componentesImages['SSD NVMe 2TB Kingston'],
    category: "componentes",
    categoryLabel: "Componentes",
    price: 189990,
    priceFormatted: "$189.990",
    imageBg: "cyan-teal",
    description: "Disco SSD NVMe de 2TB con velocidades de lectura de 7000MB/s. Gen 4 PCIe.",
    specs: ["2TB Capacidad", "7000MB/s lectura", "NVMe Gen 4", "Heat sink incluido", "5 años garantía"],
    destacado: true,
    oferta: true,
    brand: "HP",
    discount: 0,
    badgeType: "offer",
    rating: 4.8,
    reviews: 89,
    stock: 20
  },
  {
    id: 26,
    name: "Tarjeta Madre ASUS ROG Strix B650E",
    image: componentesImages['Tarjeta Madre ASUS ROG Strix B650E'],
    category: "componentes",
    categoryLabel: "Componentes",
    price: 299990,
    priceFormatted: "$299.990",
    imageBg: "purple-indigo",
    description: "Tarjeta madre AMD AM5 con soporte DDR5, PCIe 5.0 y refrigeración VRM robusta.",
    specs: ["AMD AM5", "DDR5 6400MHz", "PCIe 5.0", "WiFi 6E", "USB4"],
    destacado: true,
    oferta: false,
    brand: "ASUS",
    discount: 0,
    badgeType: "new",
    rating: 4.7,
    reviews: 56,
    stock: 8
  },
  {
    id: 27,
    name: "RAM DDR5 32GB Corsair Vengeance",
    image: componentesImages['RAM DDR5 32GB Corsair Vengeance'],
    category: "componentes",
    categoryLabel: "Componentes",
    price: 159990,
    priceFormatted: "$159.990",
    imageBg: "pink-purple",
    description: "Kit de memoria RAM DDR5 de 32GB (2x16GB) a 5600MHz con disipador de calor.",
    specs: ["32GB (2x16GB)", "DDR5 5600MHz", "CL36", "XMP 3.0", "RGB"],
    destacado: false,
    oferta: false,
    brand: "Acer",
    discount: 12,
    badgeType: "discount",
    rating: 4.6,
    reviews: 78,
    stock: 25
  },
  {
    id: 28,
    name: "Fuente 850W 80+ Gold Corsair",
    image: componentesImages['Fuente 850W 80+ Gold Corsair'],
    category: "componentes",
    categoryLabel: "Componentes",
    price: 179990,
    priceFormatted: "$179.990",
    imageBg: "blue-purple",
    description: "Fuente de poder modular 850W con certificación 80+ Gold y cables modulares.",
    specs: ["850W", "80+ Gold", "Full Modular", "Fan 135mm", "10 años garantía"],
    destacado: true,
    oferta: true,
    brand: "MSI",
    discount: 0,
    badgeType: "offer",
    rating: 4.5,
    reviews: 64,
    stock: 12
  },
  {
    id: 29,
    name: "Procesador AMD Ryzen 7 7800X3D",
    image: componentesImages['Procesador AMD Ryzen 7 7800X3D'],
    category: "componentes",
    categoryLabel: "Componentes",
    price: 349990,
    priceFormatted: "$349.990",
    imageBg: "cyan-blue",
    description: "Procesador gaming con 3D V-Cache para el máximo rendimiento en juegos.",
    specs: ["8 Cores / 16 Threads", "4.2-5.0 GHz", "104MB Cache", "AM5", "120W TDP"],
    destacado: true,
    oferta: false,
    brand: "Lenovo",
    discount: 0,
    badgeType: "new",
    rating: 4.9,
    reviews: 42,
    stock: 10
  },
  {
    id: 30,
    name: "Cooler CPU Noctua NH-D15",
    image: componentesImages['Cooler CPU Noctua NH-D15'],
    category: "componentes",
    categoryLabel: "Componentes",
    price: 129990,
    priceFormatted: "$129.990",
    imageBg: "indigo-cyan",
    description: "Disipador de calor premium con doble torre y ventiladores ultra silenciosos.",
    specs: ["Doble torre", "2x NF-A15", "220W TDP", "Ultra silencioso", "6 años garantía"],
    destacado: false,
    oferta: false,
    brand: "HP",
    discount: 8,
    badgeType: "discount",
    rating: 4.8,
    reviews: 95,
    stock: 14
  },

  // ==================== PERIFERICOS (6) ====================
  {
    id: 31,
    name: "Auriculares Gamer RGB 7.1",
    image: perifericosImages['Auriculares Gamer RGB 7.1'],
    category: "perifericos",
    categoryLabel: "Periféricos",
    price: 85500,
    priceFormatted: "$85.500",
    imageBg: "pink-purple",
    description: "Auriculares gamer inalámbricos con sonido envolvente 7.1, iluminación RGB y batería de larga duración.",
    specs: ["Sonido 7.1 Virtual", "Bluetooth 5.0", "Batería 20hs", "RGB personalizable", "Micrófono retráctil"],
    destacado: true,
    oferta: true,
    brand: "ASUS",
    discount: 0,
    badgeType: "offer",
    rating: 4.5,
    reviews: 124,
    stock: 22
  },
  {
    id: 32,
    name: "Mouse Óptico Gamer 16000 DPI",
    image: perifericosImages['Mouse Óptico Gamer 16000 DPI'],
    category: "perifericos",
    categoryLabel: "Periféricos",
    price: 45990,
    priceFormatted: "$45.990",
    imageBg: "cyan-teal",
    description: "Mouse gamer de alta precisión con sensor óptico de 16000 DPI, botones programables y RGB.",
    specs: ["16000 DPI", "8 botones", "RGB", "Cable de 1.8m", "Peso ajustable"],
    destacado: false,
    oferta: false,
    brand: "HP",
    discount: 0,
    badgeType: "new",
    rating: 4.6,
    reviews: 156,
    stock: 18
  },
  {
    id: 33,
    name: "Teclado Mecánico RGB Switch Red",
    image: perifericosImages['Teclado Mecánico RGB Switch Red'],
    category: "perifericos",
    categoryLabel: "Periféricos",
    price: 65000,
    priceFormatted: "$65.000",
    imageBg: "blue-purple",
    description: "Teclado mecánico con switches Red para gaming, iluminación RGB por tecla y construcción robusta.",
    specs: ["Switches Red", "RGB por tecla", "Aluminio", "Anti-ghosting NKRO", "USB-C desmontable"],
    destacado: true,
    oferta: false,
    brand: "Acer",
    discount: 15,
    badgeType: "discount",
    rating: 4.7,
    reviews: 98,
    stock: 30
  },
  {
    id: 34,
    name: "Monitor Curvo 27'' 165Hz Gaming",
    image: perifericosImages['Monitor Curvo 27\'\' 165Hz Gaming'],
    category: "perifericos",
    categoryLabel: "Periféricos",
    price: 420000,
    priceFormatted: "$420.000",
    imageBg: "indigo-cyan",
    description: "Monitor gamer curvo de 27 pulgadas con tasa de refresco de 165Hz y tiempo de respuesta de 1ms.",
    specs: ["27'' Curvo", "165Hz", "1ms respuesta", "FreeSync Premium", "HDR 400"],
    destacado: true,
    oferta: true,
    brand: "MSI",
    discount: 0,
    badgeType: "offer",
    rating: 4.8,
    reviews: 86,
    stock: 6
  },
  {
    id: 35,
    name: "Webcam Full HD 1080p",
    image: perifericosImages['Webcam Full HD 1080p'],
    category: "perifericos",
    categoryLabel: "Periféricos",
    price: 59990,
    priceFormatted: "$59.990",
    imageBg: "cyan-blue",
    description: "Webcam Full HD con autofocus, micrófono integrado y correctedión de luz para streaming.",
    specs: ["1080p 30fps", "Autofocus", "Micrófono dual", "USB-A", "Corrección de luz"],
    destacado: false,
    oferta: false,
    brand: "Lenovo",
    discount: 0,
    badgeType: "new",
    rating: 4.4,
    reviews: 110,
    stock: 40
  },
  {
    id: 36,
    name: "Mousepad Gamer XL RGB",
    image: perifericosImages['Mousepad Gamer XL RGB'],
    category: "perifericos",
    categoryLabel: "Periféricos",
    price: 29990,
    priceFormatted: "$29.990",
    imageBg: "purple-indigo",
    description: "Mousepad extra grande con borde cosido, superficie de tela y base antideslizante.",
    specs: ["900x400mm", "Tela de alta densidad", "Borde cosido", "Base antideslizante", "3mm grosor"],
    destacado: false,
    oferta: false,
    brand: "HP",
    discount: 10,
    badgeType: "discount",
    rating: 4.3,
    reviews: 200,
    stock: 15
  },

  // ==================== GAMING (6) ====================
  {
    id: 37,
    name: "Silla Gamer Ergonómica RGB",
    image: gamingImages['Silla Gamer Ergonómica RGB'],
    category: "gaming",
    categoryLabel: "Gaming",
    price: 389990,
    priceFormatted: "$389.990",
    imageBg: "indigo-cyan",
    description: "Silla gamer ergonómica con soporte lumbar, reposabrazos 4D e iluminación RGB lateral.",
    specs: ["Ergonómica", "RGB lateral", "Reposabrazos 4D", "Soporte lumbar", "Hasta 150kg"],
    destacado: true,
    oferta: true,
    brand: "ASUS",
    discount: 0,
    badgeType: "offer",
    rating: 4.6,
    reviews: 78,
    stock: 10
  },
  {
    id: 38,
    name: "Control Xbox Wireless Carbon Black",
    image: gamingImages['Control Xbox Wireless Carbon Black'],
    category: "gaming",
    categoryLabel: "Gaming",
    price: 89990,
    priceFormatted: "$89.990",
    imageBg: "cyan-blue",
    description: "Control inalámbrico Xbox con textura antiderrapante, gatillos con traba y batería de larga duración.",
    specs: ["Bluetooth + USB-C", "Batería AA", "Textura antiderrapante", "Triggers con traba", "Compatible PC/Xbox"],
    destacado: true,
    oferta: false,
    brand: "HP",
    discount: 0,
    badgeType: "new",
    rating: 4.7,
    reviews: 145,
    stock: 25
  },
  {
    id: 39,
    name: "Joystick Thrustmaster T300 RS GT",
    image: gamingImages['Joystick Thrustmaster T300 RS GT'],
    category: "gaming",
    categoryLabel: "Gaming",
    price: 299990,
    priceFormatted: "$299.990",
    imageBg: "purple-indigo",
    description: "Volante de racing con motor de fuerza feedback y pedalera de aluminio.",
    specs: ["Force Feedback", "Motor brushless", "Pedalera aluminio", "PS5/PC", "Volante leather"],
    destacado: true,
    oferta: false,
    brand: "Acer",
    discount: 12,
    badgeType: "discount",
    rating: 4.8,
    reviews: 56,
    stock: 8
  },
  {
    id: 40,
    name: "Consola Portátil Steam Deck 512GB",
    image: gamingImages['Consola Portátil Steam Deck 512GB'],
    category: "gaming",
    categoryLabel: "Gaming",
    price: 549990,
    priceFormatted: "$549.990",
    imageBg: "blue-purple",
    description: "Consola portátil Valve con pantalla 7'' LCD, AMD APU y 512GB de almacenamiento.",
    specs: ["AMD APU RDNA2", "16GB RAM", "512GB SSD", "7'' LCD 60Hz", "Linux/Windows"],
    destacado: true,
    oferta: false,
    brand: "MSI",
    discount: 0,
    badgeType: "new",
    rating: 4.9,
    reviews: 67,
    stock: 5
  },
  {
    id: 41,
    name: "Escritorio Gamer RGB 140cm",
    image: gamingImages['Escritorio Gamer RGB 140cm'],
    category: "gaming",
    categoryLabel: "Gaming",
    price: 449990,
    priceFormatted: "$449.990",
    imageBg: "cyan-teal",
    description: "Escritorio gamer con superficie amplia, RGB integrado, soporte para monitor y organizador de cables.",
    specs: ["140x60cm", "RGB LED", "Soporte monitor", "Organizador cables", "Carga USB integrada"],
    destacado: false,
    oferta: false,
    brand: "Lenovo",
    discount: 8,
    badgeType: "discount",
    rating: 4.5,
    reviews: 43,
    stock: 12
  },
  {
    id: 42,
    name: "Lente Cámara Streaming 4K",
    image: gamingImages['Lente Cámara Streaming 4K'],
    category: "gaming",
    categoryLabel: "Gaming",
    price: 199990,
    priceFormatted: "$199.990",
    imageBg: "pink-purple",
    description: "Cámara para streaming con lente 4K, autofoco y micrófono omnidireccional.",
    specs: ["4K 30fps", "1080p 60fps", "Autofoco", "Micrófono dual", "USB-C"],
    destacado: false,
    oferta: true,
    brand: "HP",
    discount: 0,
    badgeType: "offer",
    rating: 4.4,
    reviews: 89,
    stock: 20
  },

  // ==================== OFERTAS (6) ====================
  {
    id: 43,
    name: "Samsung Galaxy S24 128GB",
    image: ofertasImages['Samsung Galaxy S24 128GB'],
    category: "ofertas",
    categoryLabel: "Ofertas",
    price: 899990,
    priceFormatted: "$899.990",
    imageBg: "purple-indigo",
    description: "Smartphone flagship con IA Galaxy, cámara de 50MP y pantalla Dynamic AMOLED 2X.",
    specs: ["Exynos 2400", "128GB", "50MP Cámara", "4000mAh", "6.2'' AMOLED"],
    destacado: true,
    oferta: true,
    brand: "ASUS",
    discount: 20,
    badgeType: "discount",
    rating: 4.6,
    reviews: 150,
    stock: 35
  },
  {
    id: 44,
    name: "iPhone 14 128GB",
    image: ofertasImages['iPhone 14 128GB'],
    category: "ofertas",
    categoryLabel: "Ofertas",
    price: 799990,
    priceFormatted: "$799.990",
    imageBg: "cyan-blue",
    description: "iPhone con chip A15 Bionic, cámara dual de 12MP y Face ID.",
    specs: ["A15 Bionic", "128GB", "12MP Dual", "Face ID", "6.1'' OLED"],
    destacado: true,
    oferta: true,
    brand: "Lenovo",
    discount: 15,
    badgeType: "discount",
    rating: 4.7,
    reviews: 200,
    stock: 28
  },
  {
    id: 45,
    name: "ASUS TUF Gaming F15 RTX 4050",
    image: ofertasImages['ASUS TUF Gaming F15 RTX 4050'],
    category: "ofertas",
    categoryLabel: "Ofertas",
    price: 999990,
    priceFormatted: "$999.990",
    imageBg: "pink-purple",
    description: "Notebook gamer con Intel i5, 8GB RAM, RTX 4050 y pantalla 144Hz.",
    specs: ["Intel i5-12500H", "8GB DDR4", "RTX 4050 6GB", "512GB SSD", "15.6'' FHD 144Hz"],
    destacado: true,
    oferta: true,
    brand: "ASUS",
    discount: 18,
    badgeType: "discount",
    rating: 4.5,
    reviews: 86,
    stock: 15
  },
  {
    id: 46,
    name: "Teclado Logitech MX Keys S",
    image: ofertasImages['Teclado Logitech MX Keys S'],
    category: "ofertas",
    categoryLabel: "Ofertas",
    price: 149990,
    priceFormatted: "$149.990",
    imageBg: "cyan-teal",
    description: "Teclado inalámbrico premium con retroiluminación inteligente y conexión multi-dispositivo.",
    specs: ["Bluetooth + USB", "Retroiluminación", "Multi-device", "Carga USB-C", "Mac/Win"],
    destacado: false,
    oferta: true,
    brand: "HP",
    discount: 25,
    badgeType: "discount",
    rating: 4.8,
    reviews: 120,
    stock: 22
  },
  {
    id: 47,
    name: "Monitor LG 27'' 4K UHD",
    image: ofertasImages['Monitor LG 27\'\' 4K UHD'],
    category: "ofertas",
    categoryLabel: "Ofertas",
    price: 349990,
    priceFormatted: "$349.990",
    imageBg: "blue-purple",
    description: "Monitor 4K con IPS Nano Color, HDR 10 y 98% DCI-P3 para gaming y diseño.",
    specs: ["27'' IPS", "4K UHD", "144Hz", "HDR 10", "98% DCI-P3"],
    destacado: true,
    oferta: true,
    brand: "Acer",
    discount: 10,
    badgeType: "discount",
    rating: 4.6,
    reviews: 78,
    stock: 18
  },
  {
    id: 48,
    name: "Auriculares Sony WH-1000XM5",
    image: ofertasImages['Auriculares Sony WH-1000XM5'],
    category: "ofertas",
    categoryLabel: "Ofertas",
    price: 299990,
    priceFormatted: "$299.990",
    imageBg: "indigo-cyan",
    description: "Auriculares over-ear con mejor cancelación de ruido del mercado y 30hs de batería.",
    specs: ["ANC líder", "30hs batería", "Hi-Res", "Multipoint", "LDAC"],
    destacado: true,
    oferta: true,
    brand: "MSI",
    discount: 22,
    badgeType: "discount",
    rating: 4.9,
    reviews: 165,
    stock: 12
  }
];

export const getAll = () => {
  const storedVersion = localStorage.getItem(STORAGE_VERSION_KEY);
  const stored = localStorage.getItem(STORAGE_KEY);
  
  if (!stored || storedVersion !== String(CURRENT_VERSION)) {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(productosIniciales));
    localStorage.setItem(STORAGE_VERSION_KEY, String(CURRENT_VERSION));
    return productosIniciales;
  }
  const parsed = JSON.parse(stored);

  const imageMap = {};
  productosIniciales.forEach(p => { imageMap[p.id] = p.image; });
  return parsed.map(p => ({ ...p, image: p.image || imageMap[p.id] }));
};

export const getById = (id) => {
  const productos = getAll();
  return productos.find(p => p.id === Number(id));
};

export const getByCategory = (slug) => {
  const productos = getAll();
  return productos.filter(p => p.category === slug);
};

export const getDestacados = () => {
  const productos = getAll();
  return productos.filter(p => p.destacado);
};

export const search = (query) => {
  const productos = getAll();
  const lower = query.toLowerCase();
  return productos.filter(p =>
    p.name.toLowerCase().includes(lower) ||
    p.categoryLabel.toLowerCase().includes(lower)
  );
};

export const addProduct = (product) => {
  const productos = getAll();
  const newId = productos.length > 0 ? Math.max(...productos.map(p => p.id)) + 1 : 1;
  const newProduct = { ...product, id: newId };
  productos.push(newProduct);
  localStorage.setItem(STORAGE_KEY, JSON.stringify(productos));
  return newProduct;
};

export const updateProduct = (id, data) => {
  const productos = getAll();
  const index = productos.findIndex(p => p.id === id);
  if (index !== -1) {
    productos[index] = { ...productos[index], ...data, id };
    localStorage.setItem(STORAGE_KEY, JSON.stringify(productos));
  }
};

export const deleteProduct = (id) => {
  const productos = getAll();
  const filtered = productos.filter(p => p.id !== id);
  localStorage.setItem(STORAGE_KEY, JSON.stringify(filtered));
};

export const getCategories = () => {
  return [
    { slug: 'laptops', label: 'Laptops' },
    { slug: 'pc-gamer', label: 'PC Gamer' },
    { slug: 'celulares', label: 'Celulares' },
    { slug: 'accesorios', label: 'Accesorios' },
    { slug: 'componentes', label: 'Componentes' },
    { slug: 'perifericos', label: 'Periféricos' },
    { slug: 'gaming', label: 'Gaming' }
  ];
};

export const getBrands = () => {
  return ["Lenovo", "ASUS", "HP", "Acer", "MSI"];
};
